import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componets/Navbar";
import Footer from "@/componets/Footer";
import { ToastContainer } from "react-toastify";
import Nextprovider from "@/Providers/NextAuth";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nextprovider>
        <Navbar></Navbar>
        <ToastContainer></ToastContainer>
        {children}
        <Footer></Footer>
        </Nextprovider>
      </body>
    </html>
  );
}
